import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      "e2e",
      "playwright.config.ts",
      "vitest.config.ts",
      // Generated by openapi-typescript; not hand-edited, so don't lint it.
      "src/api/openapi.ts",
    ],
  },
  {
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // Numbers/booleans in template literals are idiomatic and safe.
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: true },
      ],
      // `() => setState(false)` in JSX handlers is fine.
      "@typescript-eslint/no-confusing-void-expression": [
        "error",
        { ignoreArrowShorthand: true },
      ],
      // `||` vs `??` is intentional here: empty-string/zero fallbacks are used
      // deliberately for display defaults, so auto-converting would change
      // behaviour. Left off rather than risk silent regressions.
      "@typescript-eslint/prefer-nullish-coalescing": "off",
      // Optimistic types (external JSON, indexed access) make this rule flag
      // defensive guards that are correct at runtime. Disabled to avoid
      // removing intentional safety checks.
      "@typescript-eslint/no-unnecessary-condition": "off",
    },
  },
  {
    // Test files lean on mocks and partial fixtures; relax the strictest
    // type-aware rules that fight idiomatic test doubles.
    files: ["**/*.test.{ts,tsx}", "src/test/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      // Mocks legitimately use empty bodies, fixture non-null assertions, and
      // stub signatures that don't need await/runtime evaluation.
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/require-await": "off",
      "@typescript-eslint/no-implied-eval": "off",
      "@typescript-eslint/no-base-to-string": "off",
    },
  },
);
